"""initial migration

Revision ID: 56445eae8f8e
Revises: 
Create Date: 2026-06-12 11:47:00.124107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56445eae8f8e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('doctor_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('specialty', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_index(op.f('ix_doctors_doctor_id'), 'doctors', ['doctor_id'], unique=False)
    op.create_table('patient_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('clinical_assessment', sa.JSON(), nullable=True),
    sa.Column('ultrasound_result', sa.JSON(), nullable=True),
    sa.Column('fnac_result', sa.JSON(), nullable=True),
    sa.Column('chat_history', sa.JSON(), nullable=True),
    sa.Column('conversation_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_patient_sessions_session_id'), 'patient_sessions', ['session_id'], unique=False)
    op.create_table('patients',
    sa.Column('patient_id', sa.String(length=128), nullable=False),
    sa.Column('doctor_id', sa.String(length=128), nullable=False),
    sa.Column('demographics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('medical_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('long_term_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_index(op.f('ix_patients_doctor_id'), 'patients', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_patients_patient_id'), 'patients', ['patient_id'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('doctor_id', sa.String(length=128), nullable=False),
    sa.Column('patient_id', sa.String(length=128), nullable=True),
    sa.Column('conversation_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diagnostic_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('session_summary', sa.Text(), nullable=True),
    sa.Column('is_active', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_doctor_id'), 'sessions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_sessions_patient_id'), 'sessions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('doctor_id', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_doctor_id'), 'audit_logs', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_doctor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_patient_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_doctor_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_patients_patient_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_doctor_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_patient_sessions_session_id'), table_name='patient_sessions')
    op.drop_table('patient_sessions')
    op.drop_index(op.f('ix_doctors_doctor_id'), table_name='doctors')
    op.drop_table('doctors')
    # ### end Alembic commands ###
